name: dart_tour
version: 0.1.0
flutter:
  uses-material-design: true
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  provider: ^6.0.5
dev_dependencies:
  flutter_lints: ^2.0.1
